@extends('layouts.plantilla2')
@section('tituloPagina', 'Diccionario')

@section('content')
<br>
<div><h2>Diccionario en Nàhuatl</h2></div>
<div class="container" >
    <div class="row" >
        <div class="col">
            <div class="row">
                <div class="col-sm-11 text-center">
                    <table class="table table-hover" id="table-id">
                        <thead >
                            <tr >
                                <th class="text-center">Nùmero</th>
                                <th class="text-center">Nahuatl</th>
                                <th class="text-center">Español</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1</td>
                                <td>Atl</td>
                                <td>Agua</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Amatl</td>
                                <td>Papel</td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>Acosamalutl</td>
                                <td>Arcoiris</td>
                            </tr>
                            <tr>
                                <td>4</td>
                                <td>Atoyatl</td>
                                <td>Lago</td>
                            </tr>
                            <tr>
                                <td>5</td>
                                <td>Apan</td>
                                <td>Sobre el agua</td>
                            </tr>
                            <tr>
                                <td>6</td>
                                <td>Pantle </td>
                                <td>Alcohol</td>
                            </tr>
                            <tr>
                                <td>7</td>
                                <td>Chille</td>
                                <td>Chile</td>
                            </tr>
                            <tr>
                                <td>8</td>
                                <td>Chiche</td>
                                <td>Perro</td>
                            </tr>
                            <tr>
                                <td>9</td>
                                <td>Chichiwalle</td>
                                <td>Seno</td>
                            </tr>
                            <tr>
                                <td>10</td>
                                <td>Elutl</td>
                                <td>Elote</td>
                            </tr>
                            <tr>
                                <td>11</td>
                                <td>Sihtle</td>
                                <td>Abuela</td>
                            </tr>
                            <tr>
                                <td>12</td>
                                <td>Ehkahtsolle</td>
                                <td>Nariz</td>
                            </tr>
                            <tr>
                                <td>13</td>
                                <td>Elle</td>
                                <td>Esternon</td>
                            </tr>
                            <tr>
                                <td>14</td>
                                <td>Ehkatepetl</td>
                                <td>Cerro del viento</td>
                            </tr>
                            <tr>
                                <td>15</td>
                                <td>Tepetl</td>
                                <td>Cerro</td>
                            </tr>
                            <tr>
                                <td>16</td>
                                <td>Pahtle</td>
                                <td>Medicina</td>
                            </tr>
                            <tr>
                                <td>17</td>
                                <td>Ahke</td>
                                <td>¿Quién?</td>
                            </tr>
                            <tr>
                                <td>18</td>
                                <td>Tsahtse</td>
                                <td>Grita</td>
                            </tr>
                            <tr>
                                <td>19</td>
                                <td>Ihtetl</td>
                                <td>Estómago</td>
                            </tr>
                            <tr>
                                <td>20</td>
                                <td>Nehwatl</td>
                                <td>Yo</td>
                            </tr>
                            <tr>
                                <td>21</td>
                                <td>Tehwatl</td>
                                <td>Tu</td>
                            </tr>
                            <tr>
                                <td>22</td>
                                <td>Yehwatl</td>
                                <td>El o Ella</td>
                            </tr>
                            <tr>
                                <td>23</td>
                                <td>Semilhwitl</td>
                                <td>Día</td>
                            </tr>
                            <tr>
                                <td>24</td>
                                <td>Ixhwin</td>
                                <td>Nieto</td>
                            </tr>
                            <tr>
                                <td>25</td>
                                <td>Ilhwikatl</td>
                                <td>Cielo</td>
                            </tr>
                            <tr>
                                <td>26</td>
                                <td>Ihtowa</td>
                                <td>Dice</td>
                            </tr>
                            <tr>
                                <td>27</td>
                                <td>Ichan</td>
                                <td>Su casa</td>
                            </tr>
                            <tr>
                                <td>28</td>
                                <td>Ilhwitl</td>
                                <td>Fiesta</td>
                            </tr>
                            <tr>
                                <td>29</td>
                                <td>Ichpokatl</td>
                                <td>Muchacha</td>
                            </tr>
                            <tr>
                                <td>30</td>
                                <td>Koniatl</td>
                                <td>Bebe</td>
                            </tr>
                            <tr>
                                <td>31</td>
                                <td>Koyutl</td>
                                <td>Coyote</td>
                            </tr>
                            <tr>
                                <td>32</td>
                                <td>Kaktle</td>
                                <td>Zapato</td>
                            </tr>
                            <tr>
                                <td>33</td>
                                <td>Kaxtuile</td>
                                <td>Quince</td>
                            </tr>
                            <tr>
                                <td>34</td>
                                <td>Kalihtik</td>
                                <td>Dentro de casa</td>
                            </tr>
                            <tr>
                                <td>35</td>
                                <td>Kwawitl</td>
                                <td>Árbol</td>
                            </tr>
                            <tr>
                                <td>36</td>
                                <td>Kwaktlan</td>
                                <td>Bosque</td>
                            </tr>
                            <tr>
                                <td>37</td>
                                <td>Awakwawitl</td>
                                <td>Árbol de encino</td>
                            </tr>
                            <tr>
                                <td>38</td>
                                <td>Kwalle</td>
                                <td>Bien</td>
                            </tr>
                            <tr>
                                <td>39</td>
                                <td>Kwascuchtle</td>
                                <td>Lindero</td>
                            </tr>
                            <tr>
                                <td>40</td>
                                <td>Lipia</td>
                                <td>Amarrar</td>
                            </tr>
                            <tr>
                                <td>41</td>
                                <td>Telpokatl</td>
                                <td>Joven</td>
                            </tr>
                            <tr>
                                <td>42</td>
                                <td>Ihkwilowe</td>
                                <td>Escribe</td>
                            </tr>
                            <tr>
                                <td>43</td>
                                <td>Tsilinke</td>
                                <td>Sonora</td>
                            </tr>
                            <tr>
                                <td>44</td>
                                <td>Masatl</td>
                                <td>Venado</td>
                            </tr>
                            <tr>
                                <td>45</td>
                                <td>Mahtlaktle</td>
                                <td>Dice</td>
                            </tr>
                            <tr>
                                <td>46</td>
                                <td>Mihke</td>
                                <td>Muerto</td>
                            </tr>
                            <tr>
                                <td>47</td>
                                <td>Michin</td>
                                <td>Pez</td>
                            </tr>
                            <tr>
                                <td>48</td>
                                <td>Mistle</td>
                                <td>Gato</td>
                            </tr>
                            <tr>
                                <td>49</td>
                                <td>Nikan</td>
                                <td>Aqui</td>
                            </tr>
                            <tr>
                                <td>50</td>
                                <td>Nohpaletl</td>
                                <td>Nopal</td>
                            </tr>
                            <tr>
                                <td>51</td>
                                <td>Nuchtle</td>
                                <td>Tuna</td>
                            </tr>
                            <tr>
                                <td>52</td>
                                <td>Nakatk</td>
                                <td>Carne</td>
                            </tr>
                            <tr>
                                <td>53</td>
                                <td>Ohtle</td>
                                <td>Camino</td>
                            </tr>
                            <tr>
                                <td>54</td>
                                <td>Okutl</td>
                                <td>Ocote</td>
                            </tr>
                            <tr>
                                <td>55</td>
                                <td>Ompan</td>
                                <td>Allá</td>
                            </tr>
                            <tr>
                                <td>56</td>
                                <td>Ollin</td>
                                <td>Movimiento</td>
                            </tr>
                            <tr>
                                <td>57</td>
                                <td>Pantle </td>
                                <td>Alcohol</td>
                            </tr>
                            <tr>
                                <td>58</td>
                                <td>Puktle</td>
                                <td>Humo</td>
                            </tr>
                            <tr>
                                <td>59</td>
                                <td>Pitstik</td>
                                <td>Angosto</td>
                            </tr>
                            <tr>
                                <td>60</td>
                                <td>Sokitl</td>
                                <td>Lodo</td>
                            </tr>
                            <tr>
                                <td>61</td>
                                <td>Sehpan</td>
                                <td>Primera vez</td>
                            </tr>
                            <tr>
                                <td>62</td>
                                <td>Sihtle</td>
                                <td>Abuela</td>
                            </tr>
                            <tr>
                                <td>63</td>
                                <td>Tlakatl</td>
                                <td>Persona</td>
                            </tr>
                            <tr>
                                <td>64</td>
                                <td>Tlitik</td>
                                <td>Imperactivo</td>
                            </tr>
                            <tr>
                                <td>65</td>
                                <td>Tahtle</td>
                                <td>Padre</td>
                            </tr>
                            <tr>
                                <td>66</td>
                                <td>Tepetl</td>
                                <td>Cerro</td>
                            </tr>
                            <tr>
                                <td>67</td>
                                <td>Tlapalle</td>
                                <td>Pintura</td>
                            </tr>
                            <tr>
                                <td>68</td>
                                <td>Tlitl</td>
                                <td>Fuego</td>
                            </tr>
                            <tr>
                                <td>69</td>
                                <td>Tsiktle</td>
                                <td>Chicle</td>
                            </tr>
                            <tr>
                                <td>70</td>
                                <td>Tsopelik</td>
                                <td>Dulce</td>
                            </tr>
                            <tr>
                                <td>71</td>
                                <td>Wehkapan</td>
                                <td>Alto</td>
                            </tr>
                            <tr>
                                <td>72</td>
                                <td>Witstle</td>
                                <td>Espina</td>
                            </tr>
                            <tr>
                                <td>73</td>
                                <td>Wiptla</td>
                                <td>Pasado mañana</td>
                            </tr>
                            <tr>
                                <td>74</td>
                                <td>Xokok</td>
                                <td>Agrio</td>
                            </tr>
                            <tr>
                                <td>75</td>
                                <td>Xiktle</td>
                                <td>Ombligo</td>
                            </tr>
                            <tr>
                                <td>76</td>
                                <td>Xexetik</td>
                                <td>Travieso</td>
                            </tr>
                            <tr>
                                <td>77</td>
                                <td>Xayaka</td>
                                <td>Cara</td>
                            </tr>
                            <tr>
                                <td>78</td>
                                <td>Yehuekatl</td>
                                <td>Viento</td>
                            </tr>
                            <tr>
                                <td>79</td>
                                <td>Yetl</td>
                                <td>Frijol</td>
                            </tr>
                            <tr>
                                <td>80</td>
                                <td>Axan</td>
                                <td>Hoy</td>
                            </tr>
                            <tr>
                                <td>81</td>
                                <td>Ikni</td>
                                <td>Hermano</td>
                            </tr>
                            <tr>
                                <td>82</td>
                                <td>Sowaikni</td>
                                <td>Hermana</td>
                            </tr>
                            <tr>
                                <td>83</td>
                                <td>Pille</td>
                                <td>Hijo</td>
                            </tr>
                            <tr>
                                <td>84</td>
                                <td>Nakatl</td>
                                <td>Carne</td>
                            </tr>
                            <tr>
                                <td>85</td>
                                <td>Kupix</td>
                                <td>Amigo</td>
                            </tr>
                            <tr>
                                <td>86</td>
                                <td>Notlaka</td>
                                <td>Esposo</td>
                            </tr>
                            <tr>
                                <td>87</td>
                                <td>Tlasalohke</td>
                                <td>Alumno</td>
                            </tr>
                            <tr>
                                <td>88</td>
                                <td>Pituntle</td>
                                <td>Niño</td>
                            </tr>
                            <tr>
                                <td>89</td>
                                <td>Nimitstlatlakwtia</td>
                                <td>Por favor </td>
                            </tr>
                            <tr>
                                <td>90</td>
                                <td>Nekwtle</td>
                                <td>Pulque</td>
                            </tr>
                            <tr>
                                <td>91</td>
                                <td>Xokotl</td>
                                <td>Frutas</td>
                            </tr>
                            <tr>
                                <td>92</td>
                                <td>Texocotl</td>
                                <td>Tecojote</td>
                            </tr>
                            <tr>
                                <td>93</td>
                                <td>Tlapinawistle</td>
                                <td>Tener verguenza</td>
                            </tr>
                            <tr>
                                <td>94</td>
                                <td>Tlaxkalpiktle</td>
                                <td>Taco</td>
                            </tr>
                            <tr>
                                <td>95</td>
                                <td>Pantsin</td>
                                <td>Pan</td>
                            </tr>
                            <tr>
                                <td>96</td>
                                <td>Tunaltsintle</td>
                                <td>Sol</td>
                            </tr>
                            <tr>
                                <td>97</td>
                                <td>Ixwetskistle</td>
                                <td>Sonreir</td>
                            </tr>
                            <tr>
                                <td>98</td>
                                <td>Tlakwalle</td>
                                <td>Sopa</td>
                            </tr>
                            <tr>
                                <td>99</td>
                                <td>Tuka</td>
                                <td>Sembrar</td>
                            </tr>
                            <tr>
                                <td>100</td>
                                <td>Xinotla</td>
                                <td>Siéntate</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection
@section('dataTable')

    <script>
        $(document).ready(function(){
            $('#table-id').DataTable({
                responsive: true,
                autoWidth: false,

                "language": {
                "lengthMenu": "Mostrar    "  +
                `<select class="custom-select custom-select-sm form-control form-control-sm">
                    <option value='10'>10</option>
                    <option value='25'>25</option>
                    <option value='50'>50</option>
                    <option value='100'>100</option>
                    <option value='-1'>Mostrar todos los registros</option>
                </select>  ` +
                "registros por pagina",
                "zeroRecords": "Palabra no encontrada",
                "info": "Mostrando la pagina _PAGE_ de _PAGES_",
                "infoEmpty": "No records available",
                "infoFiltered": "(filtrado de _MAX_ registros totales)",
                'search' : 'Buscar:',
                'paginate' : {
                    'next' : 'siguiente',
                    'previous' : 'Anterior'
                }
                }
            })
        })
    </script>

@endsection
